{"cells":[{"cell_type":"markdown","metadata":{"id":"z2c6JFr7juPQ"},"source":["# NB23: Exceptions\n","\n","## Programming Fundamentals\n","\n","## L.EIC/2022-23\n","#### João Correia Lopes$^{1}$, Nuno Macedo$^{1}$, Pedro Vasconcelos$^{2}$\n","$^{1}$FEUP/DEI & INESC TEC\\\n","$^{2}$FCUP/DCC & LIACC"]},{"cell_type":"markdown","metadata":{"id":"vMNfJxQ7SyGo"},"source":["> One of the most feared expressions in modern times is 'The computer is down.'\n","\n","Norman Ralph Augustine\n"]},{"cell_type":"markdown","metadata":{"id":"MZzE7pYorju5"},"source":["## Goals\n","\n","By the end of this class, the student should be able to:\n","\n","- Write code to catch and handle *runtime* exceptions that may occur during program execution\n","\n","- Raise exceptions when a program detects an error condition\n","\n","- Assert conditions that must be true during execution\n"]},{"cell_type":"markdown","metadata":{"id":"eR5Lh1jNroE2"},"source":["## Bibliography\n","\n","- Peter Wentworth, Jeffrey Elkner, Allen B. Downey, and Chris Meyers, *How to Think Like a Computer Scientist — Learning with Python 3* (Chapter 19) [[HTML](http://openbookproject.net/thinkcs/python/english3e/exceptions.html)]\n","\n","- Brad Miller and David Ranum, *How to Think Like a Computer Scientist: Interactive Edition*. Based on material by Jeffrey Elkner, Allen B. Downey, and Chris Meyers (Chapter 13) [[HTML](https://runestone.academy/ns/books/published/thinkcspy/Exceptions/toctree.html)]\n","\n","- The Python Tutorial, *8. Errors and Exceptions*, Python 3.8 documentation (Section 8) [[HTML](https://docs.python.org/3.8/tutorial/errors.html)]\n"]},{"cell_type":"markdown","source":["# 23 Exceptions"],"metadata":{"id":"tir11Iql80yq"}},{"cell_type":"markdown","metadata":{"id":"8maMPjbu5rX-"},"source":["## 23.1 Introduction"]},{"cell_type":"markdown","metadata":{"id":"gxH2AKyT7Cdv"},"source":["### Divide by zero\n","\n","- For example, dividing by zero creates an exception:\n","\n","```\n",">>> print(1/0)\n","Traceback (most recent call last):\n","File \"<interactive input>\", line 1, in <module>\n","ZeroDivisionError: integer division or modulo by zero\n","```"]},{"cell_type":"markdown","metadata":{"id":"zdz0Bg2HqFPV"},"source":["Try it:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"TtjAcogPp8Rj"},"outputs":[],"source":["print(1/0)"]},{"cell_type":"markdown","metadata":{"id":"zJtbo2t76pYB"},"source":["### Some Common Exceptions\n","\n","Here are some basic exceptions that you might encounter when writing programs:\n","\n","- `NameError` --- raised when the program cannot find a local or global name\n","\n","- `TypeError` --- raised when a function is passed an object of the inappropriate type as its argument\n","\n","- `ValueError` --- occurs when a function argument has the right type but an inappropriate value\n","\n","- `ZeroDivisionError` --- raised when you provide the second argument for a division or modulo operation as zero\n","\n","- `FileNotFoundError` --- raised when the file or directory that the program requested does not exist\n","\n","$\\Rightarrow$\n","[https://code.tutsplus.com/tutorials/](https://code.tutsplus.com/tutorials/how-to-handle-exceptions-in-python--cms-28621)"]},{"cell_type":"markdown","metadata":{"id":"2mzLdOQU5vtW"},"source":["## 23.2 Catching exceptions"]},{"cell_type":"markdown","metadata":{"id":"oL_JQkfa6z2X"},"source":["### Runtime errors\n","\n","- Whenever a runtime error occurs, it creates an **exception** object\n","\n","- The program stops the normal flow of execution and goes back throught the\n","function call stack\n","\n","- If no **handler** for the exception is found, the program terminates and Python prints out the traceback, which ends with a error message\n","\n","- The error message on the last line has two parts:\n","\n","  - the type of error before the colon, and\n","  - specifics about the error after the colon\n","\n","```\n","   >>> tup = (\"a\", \"b\", \"d\", \"d\")\n","   >>> tup[2] = \"c\"\n","   Traceback (most recent call last):\n","     File \"<interactive input>\", line 1, in <module>\n","   TypeError: 'tuple' object does not support item assignment\n","```"]},{"cell_type":"markdown","metadata":{"id":"AoJDfqp37c68"},"source":["### Catching exceptions\n","\n","- Sometimes we want to execute an operation that might cause an exception, but we don't want the program to stop\n","\n","- We can handle the exception using the `try` statement to \"wrap\" a region of code\n","\n","- The `except` statement *catches* the exception\n","\n","```\n","  filename = input(\"Enter a file name: \")\n","  try:\n","      f = open(filename, \"r\")\n","  except FileNotFoundError:\n","      print(\"There is no file named\", filename)\n","  ...\n","```\n","\n","- Each `except` statement receives the error type (e.g. `FileNotFoundError`)\n","\n","- An `else` block is executed after the `try` one, if no exception occurred\n","\n","- A `finally` block is executed in any case\n","\n","$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/try.py>"]},{"cell_type":"markdown","metadata":{"id":"NKsYN39PxAau"},"source":["### Use of the optional `else` clause\n","\n","> The use of the `else` clause is better than adding additional code to the `try` clause because it avoids accidentally catching an exception that wasn’t raised by the code being protected by the `try ... except` statement.\n","\n","$\\Rightarrow$\n","https://docs.python.org/3/tutorial/errors.html#handling-exceptions"]},{"cell_type":"markdown","metadata":{"id":"GmnVDfk6r6vu"},"source":["Try this:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Ww7MIgDTr8mj"},"outputs":[],"source":["user_input = input(\"Type a number: \")\n","\n","try:\n","    # Try do do something that could fail.\n","    user_input_as_number = float(user_input)\n","except ValueError:\n","    # This will be executed if a \"ValueError\" is raised\n","    print(\"You did not enter a number.\")\n","else:\n","    # This will be executed if no exception got raised in the \"try\"\n","    print(\"The square of your number is \", user_input_as_number**2)\n","finally:\n","    # This will be executed whether or not an exception is raised\n","    print(\"Thank you.\")"]},{"cell_type":"markdown","metadata":{"id":"YOjTB1oD77Jg"},"source":["### Catching exceptions\n","\n","![image](https://raw.githubusercontent.com/fp-leic/public/main/notebooks/23/realpython.png)\n","\n","$\\Rightarrow$ <https://realpython.com/python-exceptions/>"]},{"cell_type":"markdown","metadata":{"id":"9JrY4KXX9cKd"},"source":["### A Complete Example"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_Sy7--6L9hJ-"},"outputs":[],"source":["import math\n","\n","number_list = [10, -5, 1.2, 'apple']\n","\n","for number in number_list:\n","    try:\n","        number_factorial = math.factorial(number)\n","    except TypeError:\n","        print(\"Factorial is not supported for given input type.\")\n","    except ValueError:\n","        print(f\"Factorial only accepts positive integer values. {number}, is not a positive integer.\")\n","    else:\n","        print(f\"The factorial of {number} is {number_factorial}\")\n","    finally:\n","        print(\"Release any resources in use.\")"]},{"cell_type":"markdown","metadata":{"id":"KNoQkkuv902Z"},"source":["$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/example.py>\n"]},{"cell_type":"markdown","metadata":{"id":"3Pu5kVhr5zMl"},"source":["## 23.3 Raising exceptions"]},{"cell_type":"markdown","metadata":{"id":"jJ670867-Oqj"},"source":["### Raising our own exceptions\n","\n","- Can our program deliberately cause its own exceptions?\n","\n","- If our program detects an error condition, we can raise an exception\n","\n","- If there's a chain of calls, \"*unwinding the call stack*\" takes place until a `try ... except` is found\n","\n","```\n","  def get_age():\n","      age = int(input(\"Please enter your age: \"))\n","      if age < 0 or age > 120:\n","          # Create a new instance of an exception\n","          my_error = ValueError(f\"{age} is not a valid age\")\n","          raise my_error\n","      return age\n","```\n","\n","$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/age.py>"]},{"cell_type":"markdown","metadata":{"id":"Jv0pWmDysyC7"},"source":["Test for a valid age."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"V__D7Ng_tD5p"},"outputs":[],"source":["def get_age(age):\n","    if age < 0 or age > 120:\n","        # Create a new instance of an exception\n","        my_error = ValueError(f\"{age} is not a valid age\")\n","        raise my_error\n","    return age\n","\n","age = int(input(\"Please enter your age: \"))\n","print(get_age(age))"]},{"cell_type":"markdown","metadata":{"id":"Pasl9ZGIyH0B"},"source":["### Further to `raise`\n","\n","- Programs may name their own exceptions by creating a new exception class (see [Classes](https://docs.python.org/3/tutorial/classes.html#tut-classes) for more about Python classes).\n","\n","- Exceptions should typically be derived from the `Exception` class, either directly or indirectly.\n","\n","$\\Rightarrow$\n","https://docs.python.org/3/tutorial/errors.html#user-defined-exceptions"]},{"cell_type":"markdown","metadata":{"id":"axz8GQNb-m42"},"source":["## 23.4 Revisiting an earlier example\n","\n","- Using exception handling, we can now modify our `recursion_depth` previous example so that it stops when it reaches the maximum recursion depth allowed\n","\n","$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/rec_depth.py>"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"m4AA5m4ptvfP"},"outputs":[],"source":["def recursion_depth(number):\n","    print(\"Recursion depth number\", number)\n","    try:\n","        recursion_depth(number + 1)\n","    except RecursionError:\n","        print(f\"I cannot go any deeper into this wormhole... {number}\")\n","\n","recursion_depth(0)"]},{"cell_type":"markdown","metadata":{"id":"780WFi1k56bG"},"source":["## 23.5 The `finally` clause of the `try` statement"]},{"cell_type":"markdown","metadata":{"id":"UfF9uvny_GdJ"},"source":["### `finally`\n","\n","- A common programming pattern is to grab a resource of some kind\n","\n","- Then we perform some computation which may raise an exception, or\n","    may work without any problems\n","\n","- Whatever happens, we want to \"clean up\" the resources we grabbed\n"]},{"cell_type":"markdown","metadata":{"id":"qXR_MlunIjsS"},"source":["\n","Try it here:\n","\n","$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/show_poly.py>"]},{"cell_type":"markdown","metadata":{"id":"ADPN5Qef59xX"},"source":["## 23.6 The `assert` exceptions"]},{"cell_type":"markdown","metadata":{"id":"HEyehW0c_PSc"},"source":["### The `assert` statement (recap)\n","\n","- Assertions are statements that state a condition that is expected to\n","hold at some point in a program or function:\n","   * if the condition evaluates to True, the program carries on as if nothing happened;\n","   * if the condition evaluates to False, the program stops and throws an exception (`AssertError`);\n","\n","- The `assert` statement takes an expression and an optional message\n","\n","- Assertions can be used to check types, values of arguments and the outputs of the function\n","\n","- Assertions are used as debugging tool as it halts the program at the point where an error occurs\n","\n","$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/assert.py>"]},{"cell_type":"markdown","metadata":{"id":"taoBE-HOI43o"},"source":["Use `assert` [[Programiz]](https://www.programiz.com/python-programming/assert-statement):"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"AMlTfRgNI-Wt"},"outputs":[],"source":["def avg(marks):\n","    # Cannot divide by zero\n","    assert len(marks) != 0, \"List is empty.\"\n","    return sum(marks)/len(marks)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"5CyYK5YGJJyZ"},"outputs":[],"source":["mark2 = [55, 88, 78, 90, 79]\n","print(f\"Average of mark2: {avg(mark2)}\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"kI0hVQAhJOYS"},"outputs":[],"source":["mark1 = []\n","print(f\"Average of mark1: {avg(mark1)}\")"]},{"cell_type":"markdown","metadata":{"id":"9UikHuJm6D10"},"source":["## 23.7 Examples & Summary"]},{"cell_type":"markdown","metadata":{"id":"yoBPaWeQ_qwU"},"source":["### A common bad programming pattern\n","\n","```\n","  try:\n","      do_something()\n","  except:\n","      pass\n","```\n","\n","* This code catches **all** exceptions that may have happened in `do_something`\n","* But does not do anything to recover from them!\n","* How could we handle an error without knowning what the error is?\n","* The only thing this code does is simply *hide* the error, allowing the\n","program to carry on execution\n","* It is better to allow exceptions to propagate and only handle specific exceptions in parts of the program where we can recover  \n","\n","$\\Rightarrow$\n","<https://realpython.com/the-most-diabolical-python-antipattern/>"]},{"cell_type":"markdown","metadata":{"id":"OrlgCsDq_3nl"},"source":["### Validate user input\n","\n","```\n","  def inputNumber(message):\n","      while True:\n","          try:\n","              userInput = int(input(message))       \n","          except ValueError:\n","              print(\"Not an integer! Try again.\")\n","              continue\n","          else:\n","              return userInput\n","\n","  age = inputNumber(\"How old are you?\")\n","```"]},{"cell_type":"markdown","metadata":{"id":"vQ1RBk7c1gSm"},"source":["### An example (with a flavor of classes)\n","\n","- Do you remember playing with \"rock, scissors, paper\"\n","\n","- Now, we can do a better implementation of the game\n","\n","  - Describe an action with `enum.IntEnum`\n","  - Describe more complex rules with a dictionary\n","  - Take in user input with `input()`\n","  - Validate the input with exceptions\n","  - Make the computer choose w/ random\n","  \n","$\\Rightarrow$\n","<https://realpython.com/python-rock-paper-scissors/>\n","\n","$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/rock_scissors.py>"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"pZ41GOgh1gSm"},"outputs":[],"source":["# Describe an action with enum.IntEnum\n","\n","from enum import IntEnum\n","class Action(IntEnum):\n","    Rock = 0\n","    Paper = 1\n","    Scissors = 2\n","    Lizard = 3\n","    Spock = 4"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FAUeCFfQ1gSn"},"outputs":[],"source":["# Describe more complex rules with a dictionary\n","\n","victories = {\n","    Action.Scissors: [Action.Lizard, Action.Paper],\n","    Action.Paper: [Action.Spock, Action.Rock],\n","    Action.Rock: [Action.Lizard, Action.Scissors],\n","    Action.Lizard: [Action.Spock, Action.Paper],\n","    Action.Spock: [Action.Scissors, Action.Rock]\n","}"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"GiF33e3V1gSn"},"outputs":[],"source":["# Take in user input with input()\n","\n","def get_user_selection():\n","    choices = [f\"{action.name}[{action.value}]\" for action in Action]\n","    choices_str = \", \".join(choices)\n","    selection = int(input(f\"Enter a choice ({choices_str}): \"))\n","    action = Action(selection)\n","    return action"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Ew-rKWu41gSo"},"outputs":[],"source":["# Make the computer choose\n","\n","import random\n","def get_computer_selection():\n","    selection = random.randint(0, len(Action) - 1)\n","    action = Action(selection)\n","    return action"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_fh3NyAO1gSo"},"outputs":[],"source":["# Determine a winner based on players' choices\n","\n","def determine_winner(user_action, computer_action):\n","    defeats = victories[user_action]\n","    if user_action == computer_action:\n","        print(f\"Both players selected {user_action.name}. It's a tie!\")\n","    elif computer_action in defeats:\n","        print(f\"{user_action.name} beats {computer_action.name}! You win!\")\n","    else:\n","        print(f\"{computer_action.name} beats {user_action.name}! You lose.\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"H_GeF_m-1gSo"},"outputs":[],"source":["# Play Several Games in a Row\n","\n","while True:\n","    try:\n","        user_action = get_user_selection()\n","    except ValueError as e:\n","        range_str = f\"[0, {len(Action) - 1}]\"\n","        print(f\"Invalid selection. Enter a value in range {range_str}\")\n","        continue\n","\n","    computer_action = get_computer_selection()\n","    determine_winner(user_action, computer_action)\n","\n","    play_again = input(\"Play again? (y/n): \")\n","    if play_again.lower() != \"y\":\n","        break"]},{"cell_type":"markdown","metadata":{"id":"IFFHbKh6ABZj"},"source":["### Nested `try`\n","\n","```\n","  try:\n","      try:\n","          raise ValueError('1')\n","      except TypeError:\n","          print(\"Caught the type error\")\n","  except ValueError:\n","      print(\"Caught the value error!\")\n","```\n","\n","$\\Rightarrow$\n","<https://github.com/fp-leic/public/blob/master/lectures/23/nested_try.py>"]},{"cell_type":"markdown","metadata":{"id":"-UVqQetCKPzf"},"source":["Try the nested `try` here:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"I_mIqXjXKUZ7"},"outputs":[],"source":["try:\n","    try:\n","        raise ValueError('1')\n","    except TypeError:\n","        print(\"Caught the type error\")\n","except ValueError:\n","    print(\"Caught the value error!\")"]},{"cell_type":"markdown","metadata":{"id":"VhtzuKHpKY08"},"source":["### Nested exceptions example"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"tfYQ2Zx6KeQc"},"outputs":[],"source":["try:\n","    try:\n","        raise ValueError('1')\n","    except TypeError:\n","        pass\n","    except ValueError:\n","        print(\"Caught the inner valueError!\")\n","except ValueError:\n","    print(\"Caught the outer value error!'\")"]},{"cell_type":"markdown","metadata":{"id":"kUJSijxq0Rb9"},"source":["### A *wildcard*\n","\n","```\n","try:\n","    f = open('myfile.txt')\n","    s = f.readline()\n","    i = int(s.strip())\n","except OSError as err:\n","    print(f\"OS error: {err}\")\n","except ValueError:\n","    print(\"Could not convert data to an integer.\")\n","except:  # Use this with extreme caution\n","    print(\"Unexpected error:\", sys.exc_info()[0])\n","    raise\n","```\n","\n","$\\Rightarrow$\n","https://docs.python.org/3/tutorial/errors.html#handling-exceptions"]},{"cell_type":"markdown","metadata":{"id":"yxv_I7GoAOsR"},"source":["### Summing Up\n","\n","- After seeing the difference between syntax errors and exceptions,\n","    you learned about various ways to raise, catch, and handle\n","    exceptions in Python:\n","\n","    - `raise` allows you to throw an exception at any time\n","\n","    - `assert` enables you to verify if a certain condition is met and\n","        throw an exception if it isn't\n","\n","    - In the `try` clause, all statements are executed until an\n","        exception is encountered\n","\n","    - `except` is used to catch and handle the exception(s) that are\n","        encountered in the `try` clause\n","\n","    - `else` lets you code sections that should run only when no\n","        exceptions are encountered in the try clause\n","\n","    - `finally` enables you to execute sections of code that should\n","        always run, with or without any previously encountered\n","        exceptions"]},{"cell_type":"markdown","metadata":{"id":"SRkbeMsnrr7S"},"source":["# Further reading"]},{"cell_type":"markdown","source":["### Exceptions in Python\n","\n","Python Tutorial || Learn Python Programming -- Socratica"],"metadata":{"id":"xZypvcAcQ88g"}},{"cell_type":"code","source":["from IPython.display import YouTubeVideo\n","YouTubeVideo('nlCKrKGHSSk')"],"metadata":{"id":"PtT9ZZg_LouR"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"a6IwK-ICEfh4"},"source":["-- João Correia Lopes, Nuno Macedo & Pedro Vasconcelos"]}],"metadata":{"celltoolbar":"Slideshow","colab":{"private_outputs":true,"provenance":[{"file_id":"1PVQ2yxCmujJA3ysrrCb7xzEf7nOc8HlS","timestamp":1701879420834}],"toc_visible":true},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.5"},"rise":{"enable_chalkboard":true}},"nbformat":4,"nbformat_minor":0}